global:
  scrape_interval:     5s
  evaluation_interval: 30s
scrape_configs:
- job_name: auth-service-application
  honor_labels: true
  static_configs:
  - targets: ['auth-server-cluster-ip-service:1000']