apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server-deployment
  namespace: galaxy-services
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      component: auth-server
  template:
    metadata:
      labels:
        component: auth-server
    spec:
      imagePullSecrets:
        - name: regsecret
      containers:
        - name: auth-server
          image: ahmed/galaxy-auth-service:#BUILD_NUMBER
          ports:  
            - containerPort: 1000
          readinessProbe:
            httpGet:
              path: /auth-service/api/v1/health
              port: 1000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /auth-service/api/v1/health
              port: 1000
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /auth-service/api/v1/health
              port: 1000
            failureThreshold: 30
            periodSeconds: 10
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-server-cluster-ip-service
  namespace: galaxy-services
spec:
  type: ClusterIP
  selector:
    component: auth-server
  ports:
    - port: 1000
      targetPort: 1000
